import { Email } from './types';

export const MOCK_EMAILS: Email[] = [
  {
    id: 'email-1',
    sender: 'sarah.chen@acmecorp.com',
    subject: 'URGENT: Production API down — clients impacted',
    body: 'Hi team,\n\nOur production API has been returning 500 errors for the past 30 minutes. Three enterprise clients have already called in. We need this resolved ASAP.\n\nPlease review the logs immediately and confirm status.\n\nSarah Chen\nCTO, Acme Corp',
    received_at: '2026-06-05T14:48:00.000Z',
    composite_score: 94,
  },
  {
    id: 'email-2',
    sender: 'james.wright@partnerfirm.com',
    subject: 'Contract review — sign by Friday EOD',
    body: 'Hi,\n\nPlease find attached the revised service agreement for Q3. Legal has approved from our side.\n\nWe need your signature by Friday end of day to proceed with the engagement.\n\nBest,\nJames Wright',
    received_at: '2026-06-05T13:03:00.000Z',
    composite_score: 71,
  },
  {
    id: 'email-3',
    sender: 'priya.sharma@internal.com',
    subject: 'Q3 budget approval needed before Monday',
    body: 'Hi,\n\nThe Q3 engineering budget proposal is ready for your review and approval. Finance needs sign-off by Monday morning to proceed with vendor payments.\n\nDeck is attached. Happy to walk through it.\n\nPriya',
    received_at: '2026-06-05T11:03:00.000Z',
    composite_score: 68,
  },
  {
    id: 'email-5',
    sender: 'support-tickets@zendesk.com',
    subject: 'Customer ticket #10482: Login issue on Chrome',
    body: 'A new support ticket has been created:\n\nCustomer: TechStart Inc\nIssue: Login page spinning indefinitely on Chrome v120\nPriority: High\n\nPlease assign and respond within 4 hours per SLA.',
    received_at: '2026-06-05T07:03:00.000Z',
    composite_score: 58,
  },
  {
    id: 'email-4',
    sender: 'alex.kim@team.com',
    subject: 'Reminder: Weekly sync tomorrow 10am',
    body: 'Hi all,\n\nJust a reminder that our weekly engineering sync is tomorrow at 10am in the main conference room.\n\nAgenda: sprint review, blockers, upcoming milestones.\n\nAlex',
    received_at: '2026-06-05T09:03:00.000Z',
    composite_score: 32,
  },
  {
    id: 'email-6',
    sender: 'newsletter@techdigest.io',
    subject: 'This week in AI: GPT updates, new models',
    body: 'Hello,\n\nHere is your weekly digest of AI news and updates. This week: new model releases, industry trends, and upcoming conferences.\n\nClick here to read more.',
    received_at: '2026-06-04T15:03:00.000Z',
    composite_score: 8,
  },
];

export const MOCK_FOLDER_EMAILS: Record<string, Email[]> = {
  Inbox: MOCK_EMAILS,
  Drafts: [
    {
      id: 'draft-1',
      sender: 'sarah.chen@acmecorp.com',
      subject: 'RE: URGENT: Production API down — clients impacted',
      body: 'Hi Sarah,\n\nI am currently looking into the production 500 errors and reviewing the logging pipeline now. I will post updates within 10 minutes.\n\nThanks,\nDeveloper',
      received_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      composite_score: 85,
    },
    {
      id: 'draft-2',
      sender: 'james.wright@partnerfirm.com',
      subject: 'RE: Contract review — sign by Friday EOD',
      body: 'Hi James,\n\nI have reviewed the service agreement proposal. I will sign and return it this afternoon.\n\nBest regards,\nDeveloper',
      received_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      composite_score: 65,
    },
  ],
  Sent: [
    {
      id: 'sent-1',
      sender: 'alex.kim@team.com',
      subject: 'RE: Reminder: Weekly sync tomorrow 10am',
      body: 'Hi Alex,\n\nThanks for the reminder. I will be there. I am ready to demo the new explainable triage scoring system in the meeting.\n\nBest,\nDeveloper',
      received_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      composite_score: 30,
    },
    {
      id: 'sent-2',
      sender: 'support-tickets@zendesk.com',
      subject: 'RE: Customer ticket #10482: Login issue on Chrome',
      body: 'Hi Zendesk Team,\n\nThe Chrome v120 login loop has been diagnosed and hotfixed. The spinner issue has been successfully resolved for client TechStart Inc.\n\nThanks,\nDeveloper',
      received_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      composite_score: 55,
    },
  ],
  Spam: [
    {
      id: 'spam-1',
      sender: 'winner@lottery-bonus.net',
      subject: 'CONGRATULATIONS: You won a cash lottery award of $1,000,000!',
      body: 'Dear customer,\n\nYour email was randomly selected to receive the global mega lottery prize of $1,000,000 USD! Please reply with your full bank details, phone number, and passport scan to claim your reward instantly.',
      received_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      composite_score: 95,
    },
    {
      id: 'spam-2',
      sender: 'crypto-presale@moonshot.io',
      subject: '100x potential meme token launching - do not miss this gem!',
      body: 'Hey developer!\n\nThe next massive meme coin launches in 1 hour. Get whitelisted now to enjoy 100x gains on day 1. Click here to connect your wallet and swap tokens.',
      received_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      composite_score: 88,
    },
  ],
  Trash: [
    {
      id: 'trash-1',
      sender: 'old-company@hr.com',
      subject: 'Out of Office: Farewell party photo links',
      body: 'Hello team,\n\nHere is the link to download the photos from last Friday\'s farewell party. Note that the cloud share link expires in 48 hours.\n\nHR Team',
      received_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
      composite_score: 15,
    },
  ],
  Social: [
    {
      id: 'social-1',
      sender: 'updates@linkedin.com',
      subject: 'John Doe and 4 other people viewed your profile this week',
      body: 'Hi Manish,\n\nSee who\'s searching for you! You have 5 profile views, 2 pending connection requests, and 3 new job matches in your area. Open LinkedIn to see more.',
      received_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      composite_score: 25,
    },
    {
      id: 'social-2',
      sender: 'notify@twitter.com',
      subject: 'Trending in Tech: Neural networks, AI co-pilots',
      body: 'Here\'s what you missed on X / Twitter today:\n\n- @elonmusk tweeted about the new neural network release.\n- @openai announced its new agent framework.\n- See more trending tweets in your feed.',
      received_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
      composite_score: 22,
    },
  ],
  Promotions: [
    {
      id: 'promo-1',
      sender: 'enterprise@github.com',
      subject: 'Save 20% on GitHub Copilot seats for your team',
      body: 'Accelerate your team\'s development speed by up to 55%. Upgrade your subscription to Copilot Enterprise before June 30th and receive 20% off your annual billing.',
      received_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      composite_score: 45,
    },
    {
      id: 'promo-2',
      sender: 'info@vercel.com',
      subject: 'Introducing generative UI v0 - build frontend in seconds',
      body: 'v0 is now available for enterprise teams. Write simple prompts and watch Vercel\'s model write, build, and deploy production-ready React layouts. Try it free.',
      received_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      composite_score: 42,
    },
  ],
};
